### ISSUE TITLE
Pixel line skew between top and bottom panel halves when horizontal scrolling  - P3

### ISSUE THREAD

**Issue by xemjeff** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#338] opened 2022-10-25 08:56 UTC
When horizontal scrolling, the P3 (64x32) display shows an offset between panel top and bottom at the halfway mark.
I have 3 panels chained.  The offset increases the faster the scroll. In the image below, I am writing out the lower case letter 'L' with a delay of 4ms between scroll shifts (one pixel to the left each cycle, blank the screen, redraw the text).

Seems like it's related to #133, but it does not happen with a static display - and it gets worse the faster the scroll.

Any thoughts on what to adjust or where to look?
![pixelSkew-2](https://user-images.githubusercontent.com/8524620/197730368-173d55bd-5d91-4616-a2c8-3766d353aa94.png)

The P3 panel has this chip:
CHIPONE ICN2037BP

Here's a link to the docs for the chip:
https://olympianled.com/wp-content/uploads/2021/05/ICN2037_datasheet_EN_2017_V2.0.pdf

I tried changing the driver to ICN2038S, but that does not help - same effect.

**Comment by DarrylStrong** [comment] 2022-10-25 11:38
This is due to the panels being two seperate halves top and bottom. As the eye follows the text across the screen there is a difference where the scans are. Top line will be in the same position as the top of the bottom half. 

You can reduce the effect by getting the scan rate as high as possible (increase the clock frequency and reduce the colour depth) but it will still be there.

The other option for scrolling is to do bit manipulation on the DMA buffers themselves, I have modified the library to make the buffers public so I can then rotate the colour bits without moving the row select bits to facilitate scrolling without having to redraw the whole display.

**Comment by mrfaptastic** [comment] 2022-10-25 11:48
Hi @xemjeff, I've noticed this as well.

What version of the library are you using? 2.0.7 or what's in the repository?

What ESP32 hardware variant?

**Comment by xemjeff** [comment] 2022-10-25 14:25
> This is due to the panels being two seperate halves top and bottom. As the eye follows the text across the screen there is a difference where the scans are. Top line will be in the same position as the top of the bottom half.
> 
> You can reduce the effect by getting the scan rate as high as possible (increase the clock frequency and reduce the colour depth) but it will still be there.
> 
> The other option for scrolling is to do bit manipulation on the DMA buffers themselves, I have modified the library to make the buffers public so I can then rotate the colour bits without moving the row select bits to facilitate scrolling without having to redraw the whole display.

>> Thanks for your response @DarrylStrong. As you say the first rows (top half, bottom half) would be aligned. But that's not what we see here. Unless I misunderstand you, row 0 and row 16 are shifted in and latched at the same time.

**Comment by DarrylStrong** [comment] 2022-10-25 14:27
Yes they are shifted at the same time but row 15 isn't, it is one full scan behind
Hence the step.

**Comment by xemjeff** [comment] 2022-10-25 14:30
> 

Version (from library.json) is 2.0.6.
ESP32 VROOM 32D

I am using flipBuffer(), so I guess that GFX version of double buffering.  Is there perhaps double buffering also in the library?

**Comment by mrfaptastic** [comment] 2022-10-25 14:34
Can you post a test sketch?

**Comment by xemjeff** [comment] 2022-10-25 14:36
@DarrylStrong  OK, I don't understand what you mean - forgive my ignorance.
Row 0 to 15 are sycn'd,  Rows 16 to 31 look like one pixel ahead.
But at slower speeds (40 ms between updates), it looks more like 1/2 pixel ahead.  And statically, there is no shift.

**Comment by xemjeff** [comment] 2022-10-25 14:37
@mrfaptastic  ok - I'll put something simple together to show the effect.

**Comment by mrfaptastic** [comment] 2022-10-25 14:51
> This is due to the panels being two seperate halves top and bottom. As the eye follows the text across the screen there is a difference where the scans are. Top line will be in the same position as the top of the bottom half. 

It's not human, there seems to be some weird delay between what is pumped out to the RGB1 vs RGB2 pins.

I don't know if there's some hidden byte ordering issue or DMA update internal silicon delay. Or perhaps the boards are slow to latch the bottom half vs. top.

**Comment by DarrylStrong** [comment] 2022-10-25 15:03
it is because your eye tracks across the leds as the text moves. That is what causes scrolling text on 7 row signs to tilt.

**Comment by DarrylStrong** [comment] 2022-10-25 15:04
> 

it is because your eye tracks across the leds as the text moves. That is what causes scrolling text on 7 row signs to tilt.

**Comment by DarrylStrong** [comment] 2022-10-25 15:07
> > This is due to the panels being two seperate halves top and bottom. As the eye follows the text across the screen there is a difference where the scans are. Top line will be in the same position as the top of the bottom half.
> 
> It's not human, there seems to be some weird delay between what is pumped out to the RGB1 vs RGB2 pins.
> 
> I don't know if there's some hidden byte ordering issue or DMA update internal silicon delay. Or perhaps the boards are slow to latch the bottom half vs. top.

I have been working in the LED display industry for thirty years. Static driven led matrices smear when scrolled, row scanned tilt and column scanned get shorter. This effect is something we had to work with on one of our 16 row boards which was scanned 8:1. We had to artificailly shift one set of 8 rows sideways to remove the step.

**Comment by board707** [comment] 2022-10-25 15:43
This is just a low scan rate. I have seen this many times.
To avoid it you have to make scan rate significantly faster than scrolling. @xemjeff used 40ms as scroll delay, so your scroll rate is 25 fps. To eliminate the effect he needs update the panel 200-300 times at second.

**Comment by xemjeff** [comment] 2022-10-25 16:04
Here's a test sketch.  The skew only happens at the mid panel. I can run 6,8 ms and there is no skew if I display on the top half or the bottom half - as long as it does not cross the middle row.

@board707 the skew still happens at 20-40 ms.

Thanks to everyone for suggestions. Hopefully the test sketch will help.
[PixelSkew.zip](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/files/9862019/PixelSkew.zip)

**Comment by mrfaptastic** [comment] 2022-10-25 19:03
> This is just a low scan rate. I have seen this many times.
> To avoid it you have to make scan rate significantly faster than scrolling. @xemjeff used 40ms as scroll delay, so your scroll rate is 25 fps. To eliminate the effect he needs update the panel 200-300 times at second.

Right, so basically the DMA buffer is being outputted slower to the panels than the CPU is updating the DMA buffer and causing essentially tearing. Hmmmm.

**Comment by DarrylStrong** [comment] 2022-10-25 20:01
So this is why I don't see it as badly then as I move the dma buffers for scrolling rather than redrawing the whole screen.

**Comment by xemjeff** [comment] 2022-10-25 20:09
Why is the tearing always at the mid-line?  The data are shift loaded in parallel, the OE and LATCH are used for both.
From what I see, the bottom is updated before the top and the skew distance changes with scrolling speed.

If the CPU is updating the buffer at varying rates based on scroll rate, wouldn't the tear change row location?

**Comment by xemjeff** [comment] 2022-10-25 20:31
I think I understand what's going on:
The lower and upper panels are drawn at the same time. But the line is moving.
It takes a certain amount of time (t_k) to move through the 16 rows. What we "see" are two slanted lines, and of course they don't connect. (see figure below).  The faster the perceived movement, the greater the perceived slant.
I tool slow-motion video of the dislplay and it's fine, The pixels on top and bottom line up.

![SkewMidLine](https://user-images.githubusercontent.com/8524620/197875484-f44e2847-6b0c-4953-b937-d9eb5a936e65.png)

If this correct, then it's not tearing. I'm not sure if increasing the update rate would help. 
Let me know if you concur.

**Comment by DarrylStrong** [comment] 2022-10-25 20:35
That's exactly what I was trying to explain.

Hence why we had to offset the bottom half of our display by one pixel.

**Comment by xemjeff** [comment] 2022-10-25 20:39
@DarrylStrong  Yes - I understand now - it just took me a while :-)

I tried offsetting the bottom panel by one pixel. That works at the fast speeds.
Then of course, as we slow down the scroll, we get the reverse problem - skewing in the other direction.

I'm curious why manipulating the DMA buffer would make any difference.  This would still result in the slant effect, no?

**Comment by DarrylStrong** [comment] 2022-10-25 20:45
I didn't explain myself very well 😊


It is just faster manipulating the buffers, I am using the library for 384x64 displays so the redraw takes a while 😉

**Comment by DarrylStrong** [comment] 2022-10-25 20:47
I didn't explain myself very well 😊


It is just faster manipulating the buffers, I am using the library for 384x64 displays so the redraw takes a while 😉

It was also helped when we did this pixel shift that the scroll speed was synchronised with the scan rate.

**Comment by board707** [comment] 2022-10-25 21:00
> The lower and upper panels are drawn at the same time. But the line is moving.
> It takes a certain amount of time (t_k) to move through the 16 rows. What we "see" are two slanted lines, and of course they don't connect. (see figure below). The faster the perceived movement, the greater the perceived slant.
> I tool slow-motion video of the dislplay and it's fine, The pixels on top and bottom line up.

But I am wondering why the double buffering do not fix this artefacts. As far as understand it, with double buffering whole picture should updated in one time.

**Comment by DarrylStrong** [comment] 2022-10-25 21:08
It is written at the same time but your eyes follow the image across so see the columns in different positions as the text scrolls. Of course there are only two rows on at a time... Refer to the fantastic diagram above 😊

**Comment by xemjeff** [comment] 2022-10-25 21:12
expanding on @DarrylStrong's explanation:  

Your eye is following the line as is moves. The pixels are displayed one row at a time. (in my case one pixel per row)
From one row to the next, your eye has moved, following the line. This means that the next row is shifted on your retina by some small amount, Same for the next pixel.  This results in the perception of a slanted line.

**Comment by mrfaptastic** [comment] 2022-10-25 21:16
> Version (from library.json) is 2.0.6. ESP32 VROOM 32D
> 
> I am using flipBuffer(), so I guess that GFX version of double buffering. Is there perhaps double buffering also in the library?

That's your problem. You need to use 2.0.7

If you are using double buffering, and you give a few milliseconds from when you stop drawing to when you call 'flipDMABuffer', then you shouldn't have this issue... but only if you're using 2.0.7

**Comment by board707** [comment] 2022-10-25 21:26
> Your eye is following the line as is moves...

If it was only an optical effect, we would not see a shift in the photo, as in the first message.
I just test scrolling in the chain of two 64x32 RGB matrices with scroll delay 5ms and picture update 200fps - i don't see anything similar to your picture. The scrolling letters is absolutely straight in vertical.

**Comment by xemjeff** [comment] 2022-10-25 21:56
@mrfaptastic  I tried 2.0.7, and introduced 2ms and 4ms delay before flipping the buffer. (dbuff = true). Same shift effect.

@board707 :
did you test with the test sketch I provided, or some other implementation? If different, could you post that?
what version of the lib?  2.0.6, 2.07, etc?
where do you set 200FPS - is that the min_refresh_rate? I tried 60, 85, 200 and saw no difference.

**Comment by board707** [comment] 2022-10-25 22:21
> did you test with the test sketch I provided, or some other implementation?

Sorry, I tested just to make sure it's not an optical effect. I used completely different environment - 2x 64x32 RGB panels with RP2040 board and specific library.
(This is how the letters looks like when scrolling from left to right at a speed of 5ms/pixel. )
![P_20221026_010240_small](https://user-images.githubusercontent.com/50185434/197892608-13e80d48-72cd-45c6-bfe1-2a1c9915d6bd.jpg)

**Comment by xemjeff** [comment] 2022-10-25 22:32
@board707 has a good point. Why would it show up skewed in the slo-mo video?

I changed the code to draw a 2 pixel vertical line across the mid row.
When I shoot that video in slow motion, I see the two pixels skewed.

![twoPixelVLine](https://user-images.githubusercontent.com/8524620/197894480-9021480c-2a65-4787-a25c-384baa2919a3.png)

**Comment by xemjeff** [comment] 2022-10-26 06:17
I ran another test:

Two pixel, as above, but from left to right rather than right to left.
The skew is now reversed (the 2nd pixel now to the right of the first pixel).  

My conclusions.

* The skew is because the 2nd pixel is drawn right after the first, but in the next column as the scan begins again.

* I don't think the library is the cause.

* It's not the p3 panels. I ran the same test on P6 panels (32x32 x 3) with the same effect.

* The effect comes as the bottom row of the top sub-panel at time **'t_k**' is followed immediate by the top row of the bottom sub panel at time **t_k+1**

**Comment by board707** [comment] 2022-10-26 07:37
> * The skew is because the 2nd pixel is drawn right after the first, but in the next column as the scan begins again.

I think you are right about the nature of the effect.
Sometimes I also see something similar, but it is much weaker and rarely appears. 
Perhaps we need to take into account the shooting parameters of the camera taking photos.

**Comment by mrfaptastic** [comment] 2022-10-30 22:31
Because the delta between the top half of the panel and the bottom half is straight per the photo @xemjeff posted in the opening post, I think it's to do with the fact:

1) The Adafruit GFX library when updating any drawing activities, starts from pixel (y,x)(0,0) then scans down from left to right(0,63), (1,0) (1,63) etc.
2) By the time AdaFruit GFX has started updating rows > half the height of the panel, and hit this condition in the code: https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/blob/69686a374702613432541a135b202813aea1de8a/src/ESP32-HUB75-MatrixPanel-I2S-DMA.cpp#L302 , then the DMA buffer has probably already been output to the HUB75 panel.
I can't do much about this asynchronous timing issue between Adafruit, this library and the DMA engine. The possible solution would to fork this library and Adafruit GFX such that the draw functions return a value, and block the flipping of the DMA buffer until routines such as 'drawline' have completed.

**Comment by xemjeff** [comment] 2022-10-31 12:52
> Because the delta between the top half of the panel and the bottom half is straight per the photo @xemjeff posted in the opening post, I think it's to do with the fact:
> 
> 1. The Adafruit GFX library when updating any drawing activities, starts from pixel (y,x)(0,0) then scans down from left to right(0,63), (1,0) (1,63) etc.
> 2. By the time AdaFruit GFX updates pixels on the bottom half (i.e rows > half the height of the panel) by hitting this condition in the code: https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/blob/69686a374702613432541a135b202813aea1de8a/src/ESP32-HUB75-MatrixPanel-I2S-DMA.cpp#L302
>    
>    .... then the DMA buffer has probably already been output to the HUB75 panel.
> 
> I can't do much about this asynchronous timing issue between Adafruit GFX, this library updating SRAM and the hardware DMA engine pumping out the SRAM to the GPIOs.
> 
> However, if this is the possible root cause, I just noticed that the AdafruitGFX library has a startDraw and endDraw function that is called for every big draw primative (like drawCircle/text). So perhaps I can implement this into the library and block flipping of the DMA buffer until routines such as 'drawline' have completed. Might help.
> 
> Edit: @xemjeff, double checking your using this library as it typically is used, by leveraging the AdafruitGFX right?

I am using the Adafruit library, but for one of the simple examples (drawing a two pixel vertical line), I am calling this function:
```
    virtual void drawFastVLine(int16_t x, int16_t y, int16_t h, uint16_t color){
      uint8_t r, g, b;
      color565to888(color, r, g, b);
      vlineDMA(x, y, h, r, g, b);
    }
```

which I think bypasses Adafruit GFX.  It still exhibits the bottom panel offset (slightly advanced).

**Comment by mrfaptastic** [comment] 2022-10-31 12:58
What happens if you don't use the 'fast' line drawing function.
I'll have to look into these DMA hline and vline functions as @vortigont coded these a while back.

**Comment by mrfaptastic** [comment] 2022-11-07 01:10
> That's exactly what I was trying to explain.
> 
> Hence why we had to offset the bottom half of our display by one pixel.

Yep. In @DarrylStrong is on the mark here.

Tried to fiddle with the library to see if there's anything hacky that could help, but... obviously not.

**Comment by DarrylStrong** [comment] 2022-11-07 09:33
Thanks :)

The only way I can see of correcting this 'properly' is to sync the scrolling with the scanning and move the one half one pixel to the left to compensate for the lean. This will be quite a thing to master. Alternatively (as mentioned previously) high scan rate (reduce colour depth) will help. 

I have a sideways scroll on our 64 pixel high displays as a transition effect and it splits into 4 sections when moving but as it is only there to draw attention to change it is not important to see this anomoly.

**Comment by mrfaptastic** [comment] 2022-11-07 10:34
Not that I have tested this theory, but perhaps one should make sure the scanning direction is that of the likely graphics movement of a sketch (if it's relatively consistent).

i.e. If one is going to display heaps of graphics that scrolls from left to right (either way), then don't have the panels scanning perpendiular to this (top down), have then scan left to right or right to left as well.

Note: This would require hacking the pixel mapping code of course, but could possibly be done with the virtual matrix library.

**Comment by DarrylStrong** [comment] 2022-11-07 10:47
That would alleviate the 'tearing' for sure but might introduce a 'rippling' effect instead.

**Comment by xemjeff** [comment] 2023-03-12 00:34
Sorry the raise the dead, but I just came back to this problem today.
Looking through the code, I retested turning double buffering off, and the skew is GONE!

```
  mxconfig.double_buff = false;
  dma_display = new MatrixPanel_I2S_DMA(mxconfig);
  ```
but now, I get lots plenty of flickering. But I do wonder how does double buffering cause the skew. Is it the timing of the buffer flip?

@mrfaptastic If you are interested, I will recreate a simple sketch and re-post here with the double buffering on and off. I can also post videos.  Let me know if you want to pick this up.

**Comment by mrfaptastic** [comment] 2023-03-12 03:44
What version of the code were you using? The git master or the latest 3.0.5 release?

**Comment by mrfaptastic** [comment] 2023-03-12 03:46
Wow.

What version of the code were you using? The git master or the latest 3.0.5 release?

**Comment by xemjeff** [comment] 2023-03-13 00:41
@mrfaptastic   Here's a simple sketch, using a single P3 panel (64W x 32H). You will have to edit the `pindefs.h` file for your board configuration.

In main.cpp, change `DOUBLE_BUFFER` from `true` to `false`.  With `true`, you see the shift/skew a the mid row. With `false`, no shift/skew.

[pixelSkew2.zip](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/files/10952542/pixelSkew2.zip)

Thanks for taking a look.

**Comment by mrfaptastic** [comment] 2023-03-13 15:37
Please try again with the latest git version. The Skew with double buffering still exists as this is a optical illusion.

When turning off double buffering you don't see the skew as the whole panel is skewed because the drawing by the CPU is occuring as you see it, from top to bottom.

**Comment by xemjeff** [comment] 2023-03-14 08:21
I just built from master branch. 
Same thing.  No skew, shift or even apparent slant with double buffering off.

In the source for the `ESP32-VirtualMatrixPanel-I2S-DMA.h` file, I noticed several attempts (commented out) dealing with the timing of the buffer flip

```
    inline void flipDMABuffer() 
    {         
        if ( !m_cfg.double_buff) { return; }

        // while (active_gfx_writes) { } // wait a bit ?
      //  initialized = false;
          dma_bus.flip_dma_output_buffer( back_buffer_id ); 
    //    initialized = true;

        /*
        i2s_parallel_set_previous_buffer_not_free();       
        // Wait before we allow any writing to the buffer. Stop flicker.
        while(i2s_parallel_is_previous_buffer_free() == false) { }       
        
        i2s_parallel_flip_to_buffer(ESP32_I2S_DEVICE, back_buffer_id);        
        // Flip to other buffer as the backbuffer. 
        // i.e. Graphic changes happen to this buffer, but aren't displayed until flipDMABuffer() is called again.
        back_buffer_id ^= 1;        
        
        i2s_parallel_set_previous_buffer_not_free();       
        // Wait before we allow any writing to the buffer. Stop flicker.
        while(i2s_parallel_is_previous_buffer_free() == false) { }          
        */

    }

**Comment by board707** [comment] 2023-03-14 16:30
> Should that be synced with the DMA transfer?

No, it's the responsibility of the library.

> The shift follows the direction.

Is the shift still the same on whole height of the line? Or, are the both lines ( above and below middle-level) straight vertical?

**Comment by xemjeff** [comment] 2023-03-14 21:04
This is hard to tell - but I see the lines are alway vertical. I captured video with iPhone at 240fps (slo-mo), and the extracted frames using ffmpeg. Here is a sequence.
[ShiftSequence-240fps.zip](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/files/10973671/ShiftSequence-240fps.zip)

**Comment by mrfaptastic** [comment] 2023-03-15 14:24
You can do that, but another option could be to start from scratch using this example that Espressif's Sprite_TM created (which was actually the genesis code for the creation of this library).

Hack it right back to the bare bones just to draw a line and see if the same issue happens as well:

https://www.esp32.com/viewtopic.php?f=17&t=3188

**Comment by mrfaptastic** [comment] 2023-03-15 14:34
@xemjeff  That would be usefull to double confirm it is an issue. 

From a code perspective, one option is to start from scratch using this example that Espressif's Sprite_TM created (which was actually the genesis code for the creation of this library).

Hack it right back to the bare bones just to draw a line and see if the same issue happens as well:

https://www.esp32.com/viewtopic.php?f=17&t=3188

If I find time I will try look at this as an intellectual curiosity more than anything. A time sink this will be. Curious to see if we have this same issue on the ESP S2 and S3 devices now.

**Comment by mrfaptastic** [comment] 2023-03-16 02:32
Spent hours on this and created a basic example that only barely works. Seems I don't get the tearing issue.... hmmm...

Example uses default ESP32 pin connections.
 
[ESP32_HUB75_DoubleBufferTearingTest_2.zip](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/files/10986064/ESP32_HUB75_DoubleBufferTearingTest_2.zip)

**Comment by xemjeff** [comment] 2023-03-16 03:02
@mrfaptastic  Thanks for the zip file and for putting the time into this. I know it's nagging problem and a time sink.
This example looks like the anim ESP-IDF 64x32 LED example you mentioned in an earlier post.
I'll download and try it on a my board (different GPIO outputs) in the morning. 

Also, I'ver ordered a USB/logic analyzer with 16 channels and 400Mhz sampling rate to get a look at the signals. This would allow me to compare this working model with the output from the shifted version. Still, I will need to add a GPIO for buffer swap indicator.

**Comment by mrfaptastic** [comment] 2023-03-16 09:04
> @mrfaptastic Thanks for the zip file and for putting the time into this. I know it's nagging problem and a time sink. This example looks like the anim ESP-IDF 64x32 LED example you mentioned in an earlier post. I'll download and try it on a my board (different GPIO outputs) in the morning.

@xemjeff - Feel free to run it, but all it does is confirm that your persistence has paid off. There is an issue somewhere, and I'm sure it's a simplex fix, problem is finding the root cause.

Over the coming days I will look to see if it's an issue that has been introduced over time with this library inadvertantly. e.g. Testing the line scrolling example with version 1.1.0 of this library - problem is that version of the library doesn't compile anymore as Espressif have changed the idf so much ! Will work on it over coming days.

> 
> Also, I'ver ordered a USB/logic analyzer with 16 channels and 400Mhz sampling rate to get a look at the signals. This would allow me to compare this working model with the output from the shifted version. Still, I will need to add a GPIO for buffer swap indicator.

Wow. You mean business!

**Comment by xemjeff** [comment] 2023-03-16 15:41
@mrfaptastic The logic analyzers are fairly inexpensive. My $12 version (24Mhz) is not up to the task, and I find it very handy for protocol debugging.   I really appreciate your persistence and patience with this issue.

**Comment by mrfaptastic** [comment] 2023-03-16 21:19
OK. Here's PlatformIO Project (Arduino based) which I would like you to test when you get your logic analyzer. As far as I can see I have fixed the skew (although it is still faint).

[ESP32_HUB75_ArduinoDoubleBufferTearingTest.zip](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/files/10995939/ESP32_HUB75_ArduinoDoubleBufferTearingTest.zip)

**Comment by xemjeff** [comment] 2023-03-16 21:40
got it - thanks. I'll test with my board, and also check it out with the logic analyzer when that arrives.

**Comment by mrfaptastic** [comment] 2023-03-17 11:51
> got it - thanks. I'll test with my board, and also check it out with the logic analyzer when that arrives.

No problems. In any case I've decided to work on a new fork of this library that rewrites the core bitplane buffer alloc, DMA linked list creation and ordering (to try implement your suggestion as well about the row output ordering) etc. This should be transparent to most people, but fix this issue hopefully.

Will see what this brings, hopefully not new issues 🤣

**Comment by mrfaptastic** [comment] 2023-03-17 16:26
Don't worry about it mate. I'm going to recode it all anyway.

**Comment by mrfaptastic** [comment] 2023-03-18 20:52
Have implemented various hacks. The rewrite didn't solve the issue, but I learnt what one of the causes of the problem was - it was some weird bug.

Have added randomisation. It helps a bit, but it'll never be perfect for fast moving stuff.

**Comment by mrfaptastic** [comment] 2023-03-19 01:25
Try compiling with a global define called 'ROW_SCAN_SHUFFLE' and try without this being defined.

**Closed by mrfaptastic** 2023-03-19 01:25 UTC
Labels: not_an_issue_with_library, optical_illusion

**Comment by xemjeff** [comment] 2023-03-19 08:46
I downloaded the master branch with your recent changes. This is what I've observed:

a) The single line scroll is improved with ROW_SCAN_SHUFFLE not defined, in double buffer mode. The skew is still there, but less so.

b) In my main application with ROW_SCAN_SHUFFLE undefined, I am seeing a lot of flickering. This might be due to changes from 2.0.6 to 3.0 so I need to test that next. In my app, I am scrolling two lines at different speeds (top/bottom halves separately). That worked perfectly in 2.0.6.

c) In my main application with ROW_SCAN_SHUFFLE defined, I am seeing ghosting on the rows. Faint images of the text showing above or below the text line display.

I can capture videos and share if that will help. (flicker, ghosting, etc)

**Comment by mrfaptastic** [comment] 2023-03-19 09:27
Ok so a) is it then.

The shuffle idea doesn't look like it works. Perhaps the panels don't like being driven in random orders electrically and some residual capitance issue comes out of the woodwork causing ghosting. You can fiddle with the order in the code.

I don't see the other issues however, so I'll leave it to the signal diagnosis to see if they're are any other issues beyond the optical illusion caused by row scanning.

**Comment by xemjeff** [comment] 2023-03-20 00:11
I got the Platform.io version working [ESP32_HUB75_ArduinoDoubleBufferTearingTest.zip](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/files/10995939/ESP32_HUB75_ArduinoDoubleBufferTearingTest.zip) that you posted 3 days ago.

That version has no skew with a 10ms delay between columns shifts, so I'll build upon that. My application is quite simple - 3 horizontal panels.

Thanks for your patience and perseverance through this issue.

**Comment by mrfaptastic** [comment] 2023-03-20 15:32
I'm not sure how you get no skew, I still see it. I think it comes down to how quickly the app refreshes and the timing - so it's not consistent. Glad it worked however.

**Comment by xemjeff** [comment] 2023-03-21 03:20
@mrfaptastic Thanks for that. I posted a minor issue there regarding initialization of the gpio_matrix for the clock line.  Verified using my *newly* arrive logic analyzer.
